const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../../.env') });

const allShowcase = [
  // 4 Trending
  {
    name: 'Cardioplus Remedy',
    slug: 'cardioplus-remedy',
    genericName: 'Cardiovascular Support Complex',
    brand: 'CardioVital Labs',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 140,
    sku: 'MED-CARDIO-PLUS',
    manufacturer: 'CardioVital Laboratories',
    dosageForm: 'Capsule',
    strength: '600mg',
    packSize: 'Bottle of 60 Capsules',
    requiresPrescription: false,
    description: 'Advanced clinical cardiac support formulated with CoQ10, hawthorn berry, and magnesium.',
    shortDescription: 'Clinical cardiac support with CoQ10 & Hawthorn for vascular wellness.',
    ingredients: ['Coenzyme Q10 200mg', 'Hawthorn Berry Extract 250mg', 'Magnesium Citrate 150mg'],
    images: ['/images/medicines/cardiocare_bottle.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 382,
  },
  {
    name: 'HeartEase Solution',
    slug: 'heartease-solution',
    genericName: 'Botanical Circulatory Tincture',
    brand: 'HeartEase Botanicals',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 95,
    sku: 'MED-HEART-EASE-SOL',
    manufacturer: 'HeartEase Botanicals Inc',
    dosageForm: 'Liquid Tincture',
    strength: '30ml Dropper',
    packSize: '1 Fl Oz (30ml) Bottle',
    requiresPrescription: false,
    description: 'Organically crafted herbal heart tincture with bioactive hawthorn berry and elderberry extract.',
    shortDescription: 'Organic botanical heart tincture for steady micro-vascular flow.',
    ingredients: ['Organic Hawthorn Extract', 'Ginkgo Biloba Extract', 'Hibiscus Flower Tincture'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 298,
  },
  {
    name: 'Vasodilate Plus',
    slug: 'vasodilate-plus',
    genericName: 'Nitric Oxide Vasodilator',
    brand: 'VasoTech Bio',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 120,
    sku: 'MED-VASODILATE-PLUS',
    manufacturer: 'VasoTech Biopharma',
    dosageForm: 'Capsule',
    strength: '750mg',
    packSize: 'Bottle of 90 Capsules',
    requiresPrescription: false,
    description: 'High potency nitric oxide precursor formula supporting relaxed endothelial tissue.',
    shortDescription: 'Nitric oxide vasodilator formula for relaxed endothelial function.',
    ingredients: ['L-Arginine Alpha-Ketoglutarate', 'L-Citrulline Malate', 'Beet Root Extract'],
    images: ['/images/medicines/vasodilate_plus.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 412,
  },
  {
    name: 'BloodFlow Booster',
    slug: 'bloodflow-booster',
    genericName: 'Micro-Circulatory Support',
    brand: 'CircuLife Medical',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 80,
    sku: 'MED-BLOODFLOW-BOOST',
    manufacturer: 'CircuLife Medical Labs',
    dosageForm: 'Tablet',
    strength: '500mg',
    packSize: 'Box of 60 Film Tablets',
    requiresPrescription: false,
    description: 'Targeted bioflavonoid complex containing hesperidin and diosmin.',
    shortDescription: 'Venous circulation and micro-vascular tone support tablets.',
    ingredients: ['Micronized Purified Flavonoid Fraction 500mg', 'Hesperidin 50mg'],
    images: ['/images/medicines/bloodflow_booster.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 184,
  },
  // 3 Bento
  {
    name: 'BloodFlow Plus Formula',
    slug: 'bloodflow-plus-formula',
    genericName: 'Cardiovascular & Arterial Care',
    brand: 'VascularCare Research',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 36.99,
    discountPrice: 29.99,
    stock: 110,
    sku: 'MED-BENTO-BLOODFLOW',
    manufacturer: 'VascularCare Pharmaceuticals',
    dosageForm: 'Capsule',
    strength: '500mg',
    packSize: 'Bottle of 60 VegeCaps',
    requiresPrescription: false,
    description: 'Doctor-formulated vascular matrix featuring pine bark extract, vitamin K2-7, and magnesium malate.',
    shortDescription: 'Arterial flexibility and endothelial vascular defense.',
    ingredients: ['French Maritime Pine Bark Extract 100mg', 'Vitamin K2 (MK-7) 100mcg'],
    images: ['/images/medicines/bento_bloodflow.jpg'],
    status: 'ACTIVE',
    rating: 4.7,
    reviewCount: 520,
  },
  {
    name: 'CholestControl Advanced',
    slug: 'cholestcontrol-advanced',
    genericName: 'Lipid Balance Botanical Formula',
    brand: 'LipidCare Health',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 42.50,
    discountPrice: 34.00,
    stock: 90,
    sku: 'MED-BENTO-CHOLEST',
    manufacturer: 'LipidCare Health Sciences',
    dosageForm: 'Softgel',
    strength: '800mg',
    packSize: 'Bottle of 60 Liquid Softgels',
    requiresPrescription: false,
    description: 'Synergistic phytosterol blend combined with bergamot polyphenols and policosanol.',
    shortDescription: 'Natural lipid management and healthy arterial plaque balance.',
    ingredients: ['Plant Phytosterols 800mg', 'Bergamot Polyphenols 250mg'],
    images: ['/images/medicines/bento_cholest.jpg'],
    status: 'ACTIVE',
    rating: 4.6,
    reviewCount: 310,
  },
  {
    name: 'CardioCoQ10 Cellular Complex',
    slug: 'cardio-coq10-cellular',
    genericName: 'Active Ubiquinol CoQ10 200mg',
    brand: 'BioMito Energetics',
    categoryName: 'Vitamins & Dietary Supplements',
    price: 49.00,
    discountPrice: 39.20,
    stock: 130,
    sku: 'MED-BENTO-COQ10',
    manufacturer: 'BioMito Energetics Ltd',
    dosageForm: 'Softgel',
    strength: '200mg',
    packSize: 'Bottle of 60 Softgels',
    requiresPrescription: false,
    description: 'Enhanced bioavailability Kaneka Ubiquinol for mitochondrial cellular bioenergetics.',
    shortDescription: 'Max absorption CoQ10 Ubiquinol for cardiac cellular vitality.',
    ingredients: ['Kaneka Ubiquinol (Active CoQ10) 200mg', 'Vitamin E (d-alpha tocopherol) 15mg'],
    images: ['/images/medicines/bento_coq10.jpg'],
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 640,
  },
  // 12 Grid
  {
    name: 'PressureRelief Formula',
    slug: 'pressurerelief-formula',
    genericName: 'Florin Fast-Acting Decongestant Analgesic',
    brand: 'Florin Medical',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 220,
    sku: 'MED-FLORIN-RELIEF',
    manufacturer: 'Florin Pharmaceuticals',
    dosageForm: 'Capsule',
    strength: '500mg / 120mg',
    packSize: 'Pack of 32 Dual-Tone Capsules',
    requiresPrescription: false,
    description: 'Dual-action medical formula relieving acute pressure build-up, sinus discomfort, and cranial tension.',
    shortDescription: 'Rapid relief for cranial & systemic vascular pressure tension.',
    ingredients: ['Paracetamol 500mg', 'Pseudoephedrine HCl 120mg'],
    images: ['/images/medicines/florin_box.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 462,
  },
  {
    name: 'CardioCare Supplement',
    slug: 'cardiocare-supplement',
    genericName: 'CardioVital Heart Wellness Formula',
    brand: 'CardioVital',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 190,
    sku: 'MED-CARDIOVITAL-60',
    manufacturer: 'CardioVital Wellness Group',
    dosageForm: 'Vegetarian Capsule',
    strength: '600mg',
    packSize: 'Bottle of 60 Vegetarian Capsules',
    requiresPrescription: false,
    description: 'Targeted cardiac nutrient matrix delivering Coenzyme Q10, EPA/DHA Omega-3s, and hawthorn bioflavonoids.',
    shortDescription: 'Targeted cardiac nutrient matrix for peak myocardial contractility.',
    ingredients: ['Omega-3 Triglycerides 400mg', 'CoQ10 100mg', 'Hawthorn Extract 100mg'],
    images: ['/images/medicines/cardiocare_bottle.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 310,
  },
  {
    name: 'Hypertension Helper',
    slug: 'hypertension-helper',
    genericName: 'Digital Upper-Arm Blood Pressure Monitor',
    brand: 'HealthCheck Medical',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 85,
    sku: 'DEV-BP-MONITOR-700',
    manufacturer: 'HealthCheck Precision Instruments',
    dosageForm: 'Medical Device',
    strength: 'Clinically Validated Accuracy',
    packSize: 'Monitor Unit + Adult Arm Cuff + Storage Box',
    requiresPrescription: false,
    description: 'Hospital-grade digital upper-arm blood pressure and pulse monitor featuring WHO indicator bar.',
    shortDescription: 'Hospital-grade digital upper-arm blood pressure & pulse monitor.',
    ingredients: ['Oscillometric Pressure Sensor', 'Bio-Compatible Nylon Cuff'],
    images: ['/images/medicines/bp_monitor.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 520,
  },
  {
    name: 'VitalFlow Medicine',
    slug: 'vitalflow-medicine',
    genericName: 'Micro-Vascular Nitric Oxide Enhancer',
    brand: 'Vitality Labs',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 145,
    sku: 'MED-VITALFLOW-04',
    manufacturer: 'Vitality Pharmaceutical Care',
    dosageForm: 'Capsule',
    strength: '500mg',
    packSize: 'Pack of 60 Daily Capsules',
    requiresPrescription: false,
    description: 'Comprehensive preventative cardiovascular blend engineered to inhibit oxidative stress within coronary arteries.',
    shortDescription: 'Coronary artery protection and smooth laminar blood circulation.',
    ingredients: ['Resveratrol 150mg', 'Grape Seed Extract 200mg', 'L-Arginine 150mg'],
    images: ['/images/medicines/red_boost.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 290,
  },
  {
    name: 'CardioCare Medic',
    slug: 'cardiocare-medic',
    genericName: 'Anti-Atherosclerotic Vascular Support',
    brand: 'CardioCare',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 110,
    sku: 'MED-CARDIOCARE-MEDIC',
    manufacturer: 'Celltris UK Pharma',
    dosageForm: 'Capsule',
    strength: '40mg Active Formulation',
    packSize: 'Amber Glass Bottle of 60 Capsules',
    requiresPrescription: false,
    description: 'Clinical prescription-strength supportive remedy designed to support peripheral vessel dilation.',
    shortDescription: 'Peripheral vessel dilation and circulatory resistance relief.',
    ingredients: ['Cardioxivitamins Complex 40mg', 'Bioflavonoid Matrix 100mg'],
    images: ['/images/medicines/cardiocare_medic.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 388,
  },
  {
    name: 'HeartEase Formula',
    slug: 'heartease-formula',
    genericName: 'Bioactive Hawthorne Herbal Complex',
    brand: 'HeartEase Botanicals',
    categoryName: 'Vitamins & Dietary Supplements',
    price: 75.0,
    discountPrice: 70.0,
    stock: 130,
    sku: 'MED-HEARTEASE-HERB',
    manufacturer: 'HeartEase Botanicals LLC',
    dosageForm: 'Liquid Dropper',
    strength: '30ml Extract',
    packSize: '1 Fl Oz (30ml) Dropper Bottle',
    requiresPrescription: false,
    description: 'Holistic organic herbal tincture combining wild-harvested hawthorn berries, motherwort, and passionflower.',
    shortDescription: 'Wild-harvested organic botanical drops for balanced blood pressure.',
    ingredients: ['Hawthorn Berry Extract', 'Motherwort Aerial Parts', 'Organic Cane Alcohol'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 410,
  },
  {
    name: 'VitalHeart Solution',
    slug: 'vitalheart-solution',
    genericName: 'Ayurvedic Arjuna Cardiac Elixir',
    brand: 'VitalHeart Ayurveda',
    categoryName: 'Vitamins & Dietary Supplements',
    price: 75.0,
    discountPrice: 70.0,
    stock: 175,
    sku: 'MED-VITALHEART-SOL',
    manufacturer: 'VitalHeart Ayurvedic Science',
    dosageForm: 'Herbal Tincture',
    strength: '100% Pure Botanical',
    packSize: 'Amber Bottle with Precision Dropper 30ml',
    requiresPrescription: false,
    description: 'Time-tested Ayurvedic formulation with Terminalia Arjuna bark extract and Ashwagandha.',
    shortDescription: 'Ayurvedic Terminalia Arjuna cardiac tonic for muscular tone.',
    ingredients: ['Terminalia Arjuna Bark Extract 500mg', 'Ashwagandha Withania Somnifera 200mg'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 345,
  },
  {
    name: 'BloodFlow Plus',
    slug: 'bloodflow-plus-single',
    genericName: 'Cardiovascular Nitric Amino Stack',
    brand: 'BloodFlow Pro',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 250,
    sku: 'MED-BLOODFLOW-PLUS-SINGLE',
    manufacturer: 'CardioFlow Labs International',
    dosageForm: 'Vegetarian Capsule',
    strength: '600mg',
    packSize: 'Pack of 3 Bottles (180 Total Capsules)',
    requiresPrescription: false,
    description: 'The premier multi-bottle regimen providing round-the-clock cardiovascular, endothelial, and capillary support.',
    shortDescription: 'Premier round-the-clock vascular and endothelial bio-support.',
    ingredients: ['L-Citrulline Malate 500mg', 'Nitric Booster Blend 300mg', 'Pine Bark Extract 100mg'],
    images: ['/images/medicines/bloodflow_trio.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 680,
  },
  {
    name: 'Advanced Cardio & Lipid Lab Panel',
    slug: 'cardio-lipid-lab-panel',
    genericName: 'Diagnostic Blood Chemistry Profile',
    brand: 'Medicare Diagnostics',
    categoryName: 'Cardiovascular & Blood Pressure',
    price: 95.0,
    discountPrice: 70.0,
    stock: 500,
    sku: 'LAB-CARDIO-PANEL-01',
    manufacturer: 'Medicare Central Clinical Labs',
    dosageForm: 'Home Sample Collection / Clinic Walk-in',
    strength: '14 Vital Biomarkers',
    packSize: 'Full Verified Digital Report in 12 Hours',
    requiresPrescription: false,
    description: 'Comprehensive blood biomarker screening including Total Cholesterol, HDL/LDL, Triglycerides, and hs-CRP.',
    shortDescription: '14 vital heart biomarkers with cold-chain home nurse blood draw.',
    ingredients: ['Certified Phlebotomy Draw', 'Biochemical Serum Analysis'],
    images: ['/images/medicines/bp_monitor.jpg'],
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 512,
  },
  {
    name: 'DermaGlow Nourish Body Care',
    slug: 'dermaglow-gentle-lotion',
    genericName: 'Ceramide Prebiotic Skin Hydration',
    brand: 'DermaGlow Clinical',
    categoryName: 'Skin Care & Dermatology',
    price: 35.0,
    discountPrice: 29.0,
    stock: 310,
    sku: 'SKN-DERMAGLOW-300',
    manufacturer: 'DermaGlow Clinical Skin Science',
    dosageForm: 'Lotion + Cream Tube',
    strength: 'Dermatologist Tested',
    packSize: '300ml Pump Dispenser + 150ml Tube',
    requiresPrescription: false,
    description: 'Gentle, pediatrician and dermatologist-approved soothing lotion for sensitive skins.',
    shortDescription: 'Pediatrician-tested hypoallergenic ceramide moisture formula.',
    ingredients: ['Ceramide NP', 'Colloidal Oatmeal 2%', 'Hyaluronic Acid'],
    images: ['/images/medicines/body_lotion.jpg'],
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 420,
  },
  {
    name: 'PureGuard Antibacterial Care Gel',
    slug: 'pureguard-care-gel',
    genericName: 'Ethyl Alcohol 70% Hand Sanitizer',
    brand: 'PureGuard Health',
    categoryName: 'Antibiotics & Anti-Infectives',
    price: 28.0,
    discountPrice: 22.9,
    stock: 450,
    sku: 'HLT-PUREGUARD-500',
    manufacturer: 'PureGuard Laboratories',
    dosageForm: 'Antiseptic Gel',
    strength: '70% v/v Isopropyl Formulation',
    packSize: 'Twin Pack 2 x 500ml Dispenser Bottles',
    requiresPrescription: false,
    description: 'High efficacy antimicrobial rinse-free hand sanitizer with aloe and glycerin.',
    shortDescription: 'Kills 99.9% of pathogens with skin-calming aloe vera hydration.',
    ingredients: ['Ethyl Alcohol 70%', 'Aloe Barbadensis Leaf Juice', 'Tocopheryl Acetate'],
    images: ['/images/medicines/hand_sanitizer.jpg'],
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 630,
  },
  {
    name: 'AyurSoothe Cardamom & Arjuna Tea',
    slug: 'ayursoothe-cardiac-tea',
    genericName: 'Herbal Cardio Infusion',
    brand: 'AyurSoothe',
    categoryName: 'Vitamins & Dietary Supplements',
    price: 32.0,
    discountPrice: 26.0,
    stock: 200,
    sku: 'AYUR-TEA-ARJUNA-50',
    manufacturer: 'AyurSoothe Holistic Herbals',
    dosageForm: 'Infusion Bags',
    strength: 'Organic Whole Herbs',
    packSize: 'Tin of 40 Biodegradable Sachets',
    requiresPrescription: false,
    description: 'Delicate Ayurvedic caffeine-free infusion featuring organic Arjuna bark and holy basil (Tulsi).',
    shortDescription: 'Caffeine-free organic Arjuna & Tulsi cardiac herbal infusion.',
    ingredients: ['Arjuna Bark', 'Green Cardamom', 'Holy Basil Tulsi', 'Cinnamon'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.7,
    reviewCount: 195,
  }
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('[Seed] Connected to MongoDB Atlas');

  const categories = await mongoose.connection.collection('categories').find({}).toArray();
  const catMap = {};
  categories.forEach(c => { catMap[c.name] = c._id; });
  const defaultCatId = categories[0]._id;

  for (const med of allShowcase) {
    const catId = catMap[med.categoryName] || defaultCatId;
    const doc = {
      name: med.name,
      slug: med.slug,
      genericName: med.genericName,
      brand: med.brand,
      category: catId,
      price: med.price,
      discountPrice: med.discountPrice,
      stock: med.stock,
      sku: med.sku,
      manufacturer: med.manufacturer,
      dosageForm: med.dosageForm,
      strength: med.strength,
      packSize: med.packSize,
      requiresPrescription: med.requiresPrescription,
      description: med.description,
      shortDescription: med.shortDescription,
      ingredients: med.ingredients,
      images: med.images,
      status: med.status,
      rating: med.rating,
      reviewCount: med.reviewCount,
      updatedAt: new Date()
    };

    await mongoose.connection.collection('medicines').updateOne(
      { slug: med.slug },
      { $set: doc, $setOnInsert: { createdAt: new Date() } },
      { upsert: true }
    );
    console.log('[Seed] Synchronized:', med.name, '(' + med.slug + ')');
  }

  const finalCount = await mongoose.connection.collection('medicines').countDocuments();
  console.log('[Seed] Total medicines in database now:', finalCount);
  await mongoose.disconnect();
}

seed().catch(err => {
  console.error('[Seed Error]:', err);
  process.exit(1);
});
