import mongoose from 'mongoose';
import { connectDatabase, disconnectDatabase } from '../config/database';
import { User } from '../models/User';
import { Category } from '../models/Category';
import { Medicine } from '../models/Medicine';
import { MembershipPlan } from '../models/Membership';
import { Test, HealthCheckupPackage } from '../models/HealthCheckup';
import { Facility } from '../models/Facility';
import { hashPassword } from '../utils/password';

export async function runSeed() {
  console.log('[Seed] Connecting to MongoDB Atlas...');
  await connectDatabase();

  console.log('[System Init] Synchronizing baseline system configuration...');

  // 1. Optional Administrative User Provisioning via Environment Variables
  const initialAdminEmail = process.env.ADMIN_EMAIL;
  const initialAdminPassword = process.env.ADMIN_PASSWORD;

  if (initialAdminEmail && initialAdminPassword) {
    console.log(`[System Init] Provisioning initial administrator (${initialAdminEmail})...`);
    const hashedPassword = await hashPassword(initialAdminPassword);
    await User.findOneAndUpdate(
      { email: initialAdminEmail.toLowerCase().trim() },
      {
        $setOnInsert: {
          fullName: 'System Administrator',
          email: initialAdminEmail.toLowerCase().trim(),
          password: hashedPassword,
          role: 'ADMIN',
        },
      },
      { upsert: true, new: true }
    );
  } else {
    console.log('[System Init] No ADMIN_EMAIL/ADMIN_PASSWORD environment variables provided. Skipping admin user creation.');
  }

  // 2. Categories
  console.log('[Seed] Seeding Medicine Categories...');
  const categoriesData = [
    { name: 'Antibiotics & Anti-Infectives', slug: 'antibiotics', description: 'Clinically prescribed medications for bacterial and viral infections.', iconName: 'ShieldPlus' },
    { name: 'Cardiovascular & Blood Pressure', slug: 'cardiovascular', description: 'Medications for heart health, hypertension, and lipid control.', iconName: 'HeartPulse' },
    { name: 'Pain Relief & Analgesics', slug: 'pain-relief', description: 'Effective relief for headache, joint pain, muscle aches, and fever.', iconName: 'Pill' },
    { name: 'Diabetes Care', slug: 'diabetes-care', description: 'Glucose monitoring, insulin supplies, and metabolic management therapies.', iconName: 'Activity' },
    { name: 'Respiratory & Allergy', slug: 'respiratory-allergy', description: 'Inhalers, allergy relief antihistamines, and pulmonary aids.', iconName: 'Wind' },
    { name: 'Digestive Health & Antacids', slug: 'digestive-health', description: 'Gastrointestinal comfort, acid reflux relief, and gut probiotics.', iconName: 'Sparkles' },
    { name: 'Vitamins & Dietary Supplements', slug: 'vitamins-supplements', description: 'Essential micronutrients, immune support, and daily wellness.', iconName: 'Zap' },
    { name: 'Skin Care & Dermatology', slug: 'skin-care', description: 'Topical treatments, medicated ointments, and barrier repair lotions.', iconName: 'Droplet' },
  ];

  const categoryMap: Record<string, any> = {};
  for (const cat of categoriesData) {
    const c = await Category.findOneAndUpdate(
      { slug: cat.slug },
      { $set: cat },
      { upsert: true, new: true }
    );
    categoryMap[cat.slug] = c;
  }

  // 3. Medicines (20+ items)
  console.log('[Seed] Seeding 20+ Medicines...');
  const medicinesData = [
    {
      name: 'Amoxicillin Trihydrate 500mg',
      slug: 'amoxicillin-500mg',
      genericName: 'Amoxicillin',
      brand: 'Amoxil-Care',
      category: categoryMap['antibiotics']._id,
      price: 18.5,
      discountPrice: 14.99,
      stock: 120,
      sku: 'MED-AMOX-500',
      manufacturer: 'Apex Pharma Laboratories',
      dosageForm: 'Capsule',
      strength: '500mg',
      packSize: 'Pack of 30 Capsules',
      requiresPrescription: true,
      description: 'Amoxicillin is a penicillin-class antibiotic indicated in the treatment of bacterial infections including respiratory tract infections and ear infections.',
      shortDescription: 'Broad-spectrum antibiotic for bacterial infections.',
      ingredients: ['Amoxicillin Trihydrate 500mg'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.8,
      reviewCount: 38,
    },
    {
      name: 'Azithromycin 250mg Film-Coated',
      slug: 'azithromycin-250mg',
      genericName: 'Azithromycin',
      brand: 'ZithroMaxx',
      category: categoryMap['antibiotics']._id,
      price: 24.0,
      discountPrice: 19.5,
      stock: 85,
      sku: 'MED-AZITH-250',
      manufacturer: 'SomaCare Biopharma',
      dosageForm: 'Tablet',
      strength: '250mg',
      packSize: 'Pack of 6 Tablets',
      requiresPrescription: true,
      description: 'Macrolide antibacterial agent used for acute bacterial exacerbations of chronic bronchitis and community-acquired pneumonia.',
      shortDescription: 'Convenient 6-dose macrolide antibiotic course.',
      ingredients: ['Azithromycin 250mg'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 52,
    },
    {
      name: 'Atorvastatin Calcium 20mg',
      slug: 'atorvastatin-20mg',
      genericName: 'Atorvastatin',
      brand: 'LipidNorm',
      category: categoryMap['cardiovascular']._id,
      price: 29.99,
      discountPrice: 22.5,
      stock: 200,
      sku: 'MED-ATORV-020',
      manufacturer: 'CardioCure Therapeutics',
      dosageForm: 'Tablet',
      strength: '20mg',
      packSize: 'Bottle of 90 Tablets',
      requiresPrescription: true,
      description: 'HMG-CoA reductase inhibitor indicated as an adjunct to diet to reduce elevated total-C, LDL-C, and triglycerides.',
      shortDescription: 'Cardiovascular lipid management and cholesterol reduction.',
      ingredients: ['Atorvastatin Calcium'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.8,
      reviewCount: 76,
    },
    {
      name: 'Amlodipine Besylate 5mg',
      slug: 'amlodipine-5mg',
      genericName: 'Amlodipine',
      brand: 'NorvaCard',
      category: categoryMap['cardiovascular']._id,
      price: 16.0,
      discountPrice: 12.0,
      stock: 140,
      sku: 'MED-AMLO-005',
      manufacturer: 'CardioCure Therapeutics',
      dosageForm: 'Tablet',
      strength: '5mg',
      packSize: 'Strip of 30 Tablets',
      requiresPrescription: true,
      description: 'Calcium channel blocker for the management of hypertension and coronary artery disease.',
      shortDescription: 'Hypertension control and blood pressure regulation.',
      ingredients: ['Amlodipine Besylate'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.7,
      reviewCount: 41,
    },
    {
      name: 'Ibuprofen Extra Strength 400mg',
      slug: 'ibuprofen-400mg',
      genericName: 'Ibuprofen',
      brand: 'AdviRelief',
      category: categoryMap['pain-relief']._id,
      price: 12.99,
      discountPrice: 9.99,
      stock: 350,
      sku: 'MED-IBUP-400',
      manufacturer: 'HealthGuard Consumer',
      dosageForm: 'Softgel',
      strength: '400mg',
      packSize: 'Bottle of 100 Liquid Gels',
      requiresPrescription: false,
      description: 'Non-steroidal anti-inflammatory medication (NSAID) for fast temporary relief of headaches, toothaches, backaches, and fever.',
      shortDescription: 'Rapid pain relief and anti-inflammatory softgels.',
      ingredients: ['Solubilized Ibuprofen 400mg'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 198,
    },
    {
      name: 'Paracetamol & Acetaminophen 500mg',
      slug: 'paracetamol-500mg',
      genericName: 'Paracetamol',
      brand: 'Panadol-Plus',
      category: categoryMap['pain-relief']._id,
      price: 8.5,
      discountPrice: 6.99,
      stock: 450,
      sku: 'MED-PARA-500',
      manufacturer: 'HealthGuard Consumer',
      dosageForm: 'Tablet',
      strength: '500mg',
      packSize: 'Box of 48 Tablets',
      requiresPrescription: false,
      description: 'Gentle on stomach analgesic and antipyretic for relieving mild to moderate everyday aches and reducing body temperature.',
      shortDescription: 'Everyday pain and fever relief suitable for all adults.',
      ingredients: ['Paracetamol 500mg'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.8,
      reviewCount: 120,
    },
    {
      name: 'Metformin Hydrochloride 850mg',
      slug: 'metformin-850mg',
      genericName: 'Metformin HCl',
      brand: 'GlucoSteady',
      category: categoryMap['diabetes-care']._id,
      price: 21.0,
      discountPrice: 16.5,
      stock: 190,
      sku: 'MED-METF-850',
      manufacturer: 'Metabolic Health Corp',
      dosageForm: 'Tablet',
      strength: '850mg',
      packSize: 'Bottle of 60 Tablets',
      requiresPrescription: true,
      description: 'First-line biguanide antihyperglycemic medication for glycemic control in adult patients with type 2 diabetes.',
      shortDescription: 'Glycemic blood sugar stabilization for type 2 diabetes.',
      ingredients: ['Metformin Hydrochloride 850mg'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 65,
    },
    {
      name: 'AccuCheck Active Blood Glucose Test Strips',
      slug: 'blood-glucose-test-strips',
      genericName: 'Glucose Diagnostic Strips',
      brand: 'AccuCheck Pro',
      category: categoryMap['diabetes-care']._id,
      price: 32.5,
      discountPrice: 28.0,
      stock: 110,
      sku: 'MED-ACCU-STRIP',
      manufacturer: 'BioDiagnostic Systems',
      dosageForm: 'Medical Device',
      strength: '50 Strips',
      packSize: 'Box of 50 Test Strips',
      requiresPrescription: false,
      description: 'High accuracy self-testing blood glucose test strips for daily capillary blood monitoring with fast 5-second readouts.',
      shortDescription: 'Accurate capillary blood glucose monitoring strips.',
      ingredients: ['Glucose Oxidase Biosensor Reagents'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 88,
    },
    {
      name: 'Salbutamol Inhaler (Albuterol) 100mcg',
      slug: 'salbutamol-inhaler-100mcg',
      genericName: 'Salbutamol Sulfate',
      brand: 'VentiBreathe',
      category: categoryMap['respiratory-allergy']._id,
      price: 28.0,
      discountPrice: 22.0,
      stock: 130,
      sku: 'MED-SALB-100',
      manufacturer: 'PulmoMed Technologies',
      dosageForm: 'Metered Dose Inhaler',
      strength: '100mcg/actuation',
      packSize: '200 Metered Inhalations',
      requiresPrescription: true,
      description: 'Selective beta2-adrenergic agonist providing fast bronchodilation for the relief of bronchospasm in asthma and COPD.',
      shortDescription: 'Rapid relief rescue inhaler for wheezing and asthma symptoms.',
      ingredients: ['Salbutamol Sulfate Micro-crystalline'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 5.0,
      reviewCount: 145,
    },
    {
      name: 'Cetirizine Hydrochloride 10mg All-Day Allergy',
      slug: 'cetirizine-10mg',
      genericName: 'Cetirizine HCl',
      brand: 'ZyrtecClear',
      category: categoryMap['respiratory-allergy']._id,
      price: 15.0,
      discountPrice: 11.5,
      stock: 280,
      sku: 'MED-CETI-010',
      manufacturer: 'HealthGuard Consumer',
      dosageForm: 'Tablet',
      strength: '10mg',
      packSize: 'Bottle of 60 Mini Tablets',
      requiresPrescription: false,
      description: 'Non-drowsy 24-hour antihistamine relief against pollen allergies, hay fever, sneezing, runny nose, and itchy watery eyes.',
      shortDescription: '24-hour non-drowsy seasonal allergy relief.',
      ingredients: ['Cetirizine HCl 10mg'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.8,
      reviewCount: 92,
    },
    {
      name: 'Omeprazole Delayed-Release Capsules 20mg',
      slug: 'omeprazole-20mg',
      genericName: 'Omeprazole',
      brand: 'Prilosec-Care',
      category: categoryMap['digestive-health']._id,
      price: 22.5,
      discountPrice: 17.99,
      stock: 175,
      sku: 'MED-OMEP-020',
      manufacturer: 'GastroZen BioLabs',
      dosageForm: 'Capsule',
      strength: '20mg',
      packSize: 'Pack of 28 Capsules (Two 14-day courses)',
      requiresPrescription: false,
      description: 'Proton pump inhibitor (PPI) that decreases stomach acid production for effective relief from frequent heartburn and acid reflux.',
      shortDescription: '24-hour heartburn acid block course.',
      ingredients: ['Omeprazole Magnesium 20.6mg'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 104,
    },
    {
      name: 'Multi-Strain Daily Probiotics 50 Billion CFU',
      slug: 'daily-probiotics-50b',
      genericName: 'Lactobacillus & Bifidobacterium Complex',
      brand: 'FloraBiome Vitality',
      category: categoryMap['digestive-health']._id,
      price: 38.0,
      discountPrice: 29.99,
      stock: 90,
      sku: 'MED-FLOR-50B',
      manufacturer: 'BioNutra Organics',
      dosageForm: 'Delayed Release Capsule',
      strength: '50 Billion Live Cultures',
      packSize: 'Bottle of 60 Vegetarian Capsules',
      requiresPrescription: false,
      description: '14 diverse probiotic strains with prebiotic chicory inulin to support gut flora diversity, nutrient absorption, and digestive defense.',
      shortDescription: 'Potent 50 Billion CFU gut microbiome defense.',
      ingredients: ['Lactobacillus acidophilus', 'Bifidobacterium lactis', 'Inulin Prebiotic'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 68,
    },
    {
      name: 'Liposomal Vitamin C 1000mg with Zinc',
      slug: 'liposomal-vitamin-c-1000mg',
      genericName: 'Sodium Ascorbate & Zinc Gluconate',
      brand: 'ImmunoShield Pro',
      category: categoryMap['vitamins-supplements']._id,
      price: 24.5,
      discountPrice: 19.99,
      stock: 220,
      sku: 'MED-VITC-1000',
      manufacturer: 'BioNutra Organics',
      dosageForm: 'Capsule',
      strength: '1000mg Vit C + 15mg Zinc',
      packSize: 'Bottle of 90 Vegan Capsules',
      requiresPrescription: false,
      description: 'Advanced liposomal delivery for maximum cellular bioavailability, antioxidant protection, collagen synthesis, and seasonal immune resilience.',
      shortDescription: 'High-absorption immune defense with enhanced bioavailability.',
      ingredients: ['Liposomal Pure Vitamin C', 'Zinc Gluconate'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 5.0,
      reviewCount: 154,
    },
    {
      name: 'Vitamin D3 5000 IU + K2 (MK-7)',
      slug: 'vitamin-d3-k2-5000iu',
      genericName: 'Cholecalciferol & Menaquinone-7',
      brand: 'SolarBone Health',
      category: categoryMap['vitamins-supplements']._id,
      price: 21.0,
      discountPrice: 16.99,
      stock: 310,
      sku: 'MED-VITD-5000',
      manufacturer: 'BioNutra Organics',
      dosageForm: 'Liquid Softgel in Organic Coconut Oil',
      strength: '5000 IU D3 + 100mcg K2',
      packSize: 'Bottle of 120 Mini Softgels',
      requiresPrescription: false,
      description: 'Synergistic pairing of Vitamin D3 and K2 ensures calcium is properly deposited into bones and teeth rather than arterial walls.',
      shortDescription: 'Optimal bone density and cardiovascular calcium routing.',
      ingredients: ['Vitamin D3', 'Vitamin K2 (MK-7)', 'MCT Oil'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 230,
    },
    {
      name: 'Triple Strength Omega-3 Fish Oil 1400mg',
      slug: 'triple-strength-omega-3',
      genericName: 'Purified Marine Triglyceride Concentrate',
      brand: 'NordicVital Pure',
      category: categoryMap['vitamins-supplements']._id,
      price: 34.0,
      discountPrice: 27.5,
      stock: 140,
      sku: 'MED-OMEG-1400',
      manufacturer: 'BioNutra Organics',
      dosageForm: 'Softgel',
      strength: '900mg Active EPA/DHA',
      packSize: 'Bottle of 90 Enteric Coated Softgels',
      requiresPrescription: false,
      description: 'Molecularly distilled deep-sea fish oil providing concentrated EPA and DHA for heart health, cognitive function, and joint comfort.',
      shortDescription: 'Purified, burp-free high EPA/DHA marine omega-3.',
      ingredients: ['Wild Caught Deep Sea Fish Oil', 'Natural Tocopherols'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.8,
      reviewCount: 95,
    },
    {
      name: 'Hydrocortisone Maximum Strength Cream 1%',
      slug: 'hydrocortisone-cream-1-percent',
      genericName: 'Hydrocortisone',
      brand: 'DermaCalm Pro',
      category: categoryMap['skin-care']._id,
      price: 9.99,
      discountPrice: 7.99,
      stock: 160,
      sku: 'MED-HYDR-001',
      manufacturer: 'Dermacare Specialties',
      dosageForm: 'Topical Cream',
      strength: '1% w/w',
      packSize: '2 oz (56g) Tube',
      requiresPrescription: false,
      description: 'Fast soothing anti-itch cream for eczema, insect bites, poison ivy, dermatitis, and minor skin irritations.',
      shortDescription: 'Maximum strength soothing anti-itch topical cream.',
      ingredients: ['Hydrocortisone 10mg/g', 'Aloe Vera Leaf Juice', 'Ceramides'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.7,
      reviewCount: 56,
    },
    {
      name: 'Mupirocin Ointment USP 2%',
      slug: 'mupirocin-ointment-2-percent',
      genericName: 'Mupirocin',
      brand: 'BactroShield',
      category: categoryMap['skin-care']._id,
      price: 26.0,
      discountPrice: 20.0,
      stock: 75,
      sku: 'MED-MUPI-002',
      manufacturer: 'Dermacare Specialties',
      dosageForm: 'Topical Ointment',
      strength: '20mg/g (2%)',
      packSize: '22g Aluminum Tube',
      requiresPrescription: true,
      description: 'Prescription antibiotic ointment for topical treatment of impetigo and traumatic skin lesions infected with Staph and Strep.',
      shortDescription: 'Prescription topical antibiotic ointment for wound infections.',
      ingredients: ['Mupirocin 2% in water miscible polyethylene glycol base'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 44,
    },
    {
      name: 'Sertraline Hydrochloride 50mg',
      slug: 'sertraline-50mg',
      genericName: 'Sertraline HCl',
      brand: 'ZoloSerene',
      category: categoryMap['pain-relief']._id,
      price: 25.0,
      discountPrice: 19.0,
      stock: 110,
      sku: 'MED-SERT-050',
      manufacturer: 'Apex Pharma Laboratories',
      dosageForm: 'Scored Tablet',
      strength: '50mg',
      packSize: 'Bottle of 30 Tablets',
      requiresPrescription: true,
      description: 'Selective serotonin reuptake inhibitor (SSRI) prescribed under medical guidance for major depressive episode and panic management.',
      shortDescription: 'Prescription SSRI for mood and panic regulation.',
      ingredients: ['Sertraline Hydrochloride 50mg'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.7,
      reviewCount: 61,
    },
    {
      name: 'Levothyroxine Sodium 75mcg',
      slug: 'levothyroxine-75mcg',
      genericName: 'Levothyroxine Sodium',
      brand: 'ThyroSteady',
      category: categoryMap['cardiovascular']._id,
      price: 18.0,
      discountPrice: 14.5,
      stock: 195,
      sku: 'MED-LEVO-075',
      manufacturer: 'EndoHealth Pharmaceuticals',
      dosageForm: 'Tablet',
      strength: '75mcg (0.075mg)',
      packSize: 'Bottle of 90 Tablets',
      requiresPrescription: true,
      description: 'Synthetic thyroid hormone T4 replacement therapy for patients with primary, secondary, or tertiary hypothyroidism.',
      shortDescription: 'Synthetic T4 replacement for hypothyroidism.',
      ingredients: ['Levothyroxine Sodium Hydrate'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.8,
      reviewCount: 82,
    },
    {
      name: 'Montelukast Sodium 10mg Chewable',
      slug: 'montelukast-10mg',
      genericName: 'Montelukast',
      brand: 'SingulAir Care',
      category: categoryMap['respiratory-allergy']._id,
      price: 29.0,
      discountPrice: 22.0,
      stock: 80,
      sku: 'MED-MONT-010',
      manufacturer: 'PulmoMed Technologies',
      dosageForm: 'Tablet',
      strength: '10mg',
      packSize: 'Box of 30 Film-Coated Tablets',
      requiresPrescription: true,
      description: 'Leukotriene receptor antagonist for prophylaxis and chronic treatment of bronchial asthma and relief of allergic rhinitis symptoms.',
      shortDescription: 'Leukotriene inhibitor for asthma prevention and seasonal rhinitis.',
      ingredients: ['Montelukast Sodium 10.4mg'],
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 57,
    },
    {
      name: 'Melatonin 5mg Dual-Release Sleep Aid',
      slug: 'melatonin-5mg-dual-release',
      genericName: 'Melatonin Micronized',
      brand: 'RestWell Nocturne',
      category: categoryMap['vitamins-supplements']._id,
      price: 14.99,
      discountPrice: 11.99,
      stock: 260,
      sku: 'MED-MELA-005',
      manufacturer: 'HealthGuard Consumer',
      dosageForm: 'Dual Layer Tablet',
      strength: '5mg',
      packSize: 'Bottle of 100 Tablets',
      requiresPrescription: false,
      description: 'Immediate release layer helps fall asleep faster while extended release layer supports undisturbed night-time sleep cycles.',
      shortDescription: 'Dual-action fast and sustained natural circadian sleep support.',
      ingredients: ['Melatonin 5mg', 'Chamomile Extract', 'L-Theanine 50mg'],
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400'],
      rating: 4.9,
      reviewCount: 140,
    },
  ];

  const createdMedicines: any[] = [];
  for (const m of medicinesData) {
    const med = await Medicine.findOneAndUpdate(
      { slug: m.slug },
      { $set: m },
      { upsert: true, new: true }
    );
    createdMedicines.push(med);
  }

  // 4. Diagnostics & Tests (20+ tests)
  console.log('[Seed] Seeding 20+ Diagnostic Lab Tests...');
  const testsData = [
    { name: 'Complete Blood Count (CBC) with Differential', code: 'TEST-CBC-01', category: 'Hematology', sampleType: 'Whole Blood', price: 25, description: 'Measures white cells, red cells, platelets, hemoglobin, and hematocrit.' },
    { name: 'Comprehensive Metabolic Panel (CMP-14)', code: 'TEST-CMP-14', category: 'Biochemistry', sampleType: 'Serum Blood', price: 40, description: 'Evaluates liver function, kidney health, blood glucose, and fluid balance.' },
    { name: 'Lipid Profile Panel (Total, HDL, LDL, VLDL, Trigs)', code: 'TEST-LIPID-01', category: 'Cardiology', sampleType: 'Fasting Blood', price: 35, description: 'Cardiovascular risk assessment measuring all cholesterol fractions.' },
    { name: 'Hemoglobin A1c (HbA1c) Glycated', code: 'TEST-HBA1C', category: 'Endocrinology', sampleType: 'Whole Blood', price: 30, description: 'Estimates 3-month average blood glucose control for diabetes.' },
    { name: 'Thyroid Stimulating Hormone (TSH) Ultra-sensitive', code: 'TEST-TSH-01', category: 'Endocrinology', sampleType: 'Serum Blood', price: 32, description: 'Screening for hyperthyroidism and hypothyroidism.' },
    { name: 'Free T3 & Free T4 Panel', code: 'TEST-FT34-01', category: 'Endocrinology', sampleType: 'Serum Blood', price: 45, description: 'Measures active circulating thyroid hormones.' },
    { name: 'Vitamin D, 25-Hydroxy Total', code: 'TEST-VITD-25', category: 'Nutritional', sampleType: 'Serum Blood', price: 45, description: 'Determines vitamin D deficiency impacting bone and immunity.' },
    { name: 'Vitamin B12 & Folate Serum', code: 'TEST-VITB12', category: 'Nutritional', sampleType: 'Serum Blood', price: 42, description: 'Screens for megaloblastic anemia and neuropathy causes.' },
    { name: 'Urinalysis Complete with Microscopic Exam', code: 'TEST-URINE-01', category: 'Pathology', sampleType: 'Clean Catch Urine', price: 20, description: 'Detects urinary tract infections, kidney disorders, and metabolic indicators.' },
    { name: 'High-Sensitivity C-Reactive Protein (hs-CRP)', code: 'TEST-HSCRP', category: 'Cardiology', sampleType: 'Serum Blood', price: 38, description: 'Systemic inflammatory marker for arterial inflammation.' },
    { name: 'Serum Creatinine & Estimated GFR', code: 'TEST-EGFR-01', category: 'Nephrology', sampleType: 'Serum Blood', price: 22, description: 'Direct evaluation of renal filtration and kidney health.' },
    { name: 'Liver Function Test (LFT: ALT, AST, ALP, Bilirubin)', code: 'TEST-LFT-01', category: 'Hepatology', sampleType: 'Serum Blood', price: 35, description: 'Detects hepatic cell damage, enzyme levels, and bile flow.' },
    { name: 'Uric Acid Serum Test', code: 'TEST-URIC-01', category: 'Biochemistry', sampleType: 'Serum Blood', price: 20, description: 'Screens for hyperuricemia, gout risk, and kidney stone evaluation.' },
    { name: 'Ferritin & Total Iron Binding Capacity (TIBC)', code: 'TEST-FERR-01', category: 'Hematology', sampleType: 'Fasting Blood', price: 48, description: 'Assesses body iron storage reserves and iron-deficiency anemia.' },
    { name: 'Resting 12-Lead Electrocardiogram (ECG)', code: 'TEST-ECG-12', category: 'Cardiology', sampleType: 'Physiological Reading', price: 50, description: 'Records electrical impulses of the heart to detect arrhythmias and ischemic changes.' },
    { name: 'Chest X-Ray Digital PA View', code: 'TEST-CXR-DIG', category: 'Radiology', sampleType: 'Radiographic Imaging', price: 55, description: 'Visualizes lungs, heart border, airways, and thoracic cavity.' },
    { name: 'Abdominal & Pelvic Ultrasound Sonogram', code: 'TEST-US-ABDO', category: 'Radiology', sampleType: 'Ultrasound Imaging', price: 95, description: 'Non-invasive high frequency acoustic scan of liver, kidneys, pancreas, and spleen.' },
    { name: 'Prostate-Specific Antigen (PSA) Total', code: 'TEST-PSA-01', category: 'Oncology', sampleType: 'Serum Blood', price: 38, description: 'Screening for benign prostatic hyperplasia and prostate abnormalities.' },
    { name: 'Electrolytes Panel (Na, K, Cl, CO2)', code: 'TEST-ELEC-04', category: 'Biochemistry', sampleType: 'Serum Blood', price: 28, description: 'Evaluates hydration state, acid-base equilibrium, and cellular balance.' },
    { name: 'Fasting Blood Glucose (FBS)', code: 'TEST-FBS-01', category: 'Endocrinology', sampleType: 'Fasting Plasma', price: 15, description: 'Standard baseline assessment of morning plasma glucose.' },
    { name: 'Erythrocyte Sedimentation Rate (ESR)', code: 'TEST-ESR-01', category: 'Hematology', sampleType: 'Whole Blood', price: 18, description: 'Non-specific marker for acute inflammation and autoimmune conditions.' },
  ];

  const createdTests: any[] = [];
  for (const t of testsData) {
    const test = await Test.findOneAndUpdate(
      { code: t.code },
      { $set: t },
      { upsert: true, new: true }
    );
    createdTests.push(test);
  }

  // 5. Checkup Packages (5+ packages)
  console.log('[Seed] Seeding Health Checkup Packages...');
  const packagesData = [
    {
      name: 'Essential Wellness Basic Checkup',
      slug: 'essential-wellness-basic-checkup',
      description: 'An essential health checkup recommended annually for young adults to establish baseline biomarkers and detect asymptomatic conditions early.',
      shortDescription: 'Core blood, kidney, liver, and urinalysis screening.',
      price: 120,
      discountPrice: 89,
      duration: '1.5 Hours',
      testCount: 5,
      includedTests: [createdTests[0]._id, createdTests[1]._id, createdTests[8]._id, createdTests[19]._id, createdTests[20]._id],
      recommendedFor: 'Adults aged 18-35 for yearly preventative monitoring',
      image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=400',
    },
    {
      name: 'Comprehensive Executive Health Panel',
      slug: 'comprehensive-executive-health-panel',
      description: 'Extensive multi-system diagnostic review incorporating complete metabolic profile, full cardiovascular lipid markers, thyroid screen, and abdominal sonogram.',
      shortDescription: 'Complete 360-degree health assessment for busy professionals.',
      price: 299,
      discountPrice: 229,
      duration: '3 Hours',
      testCount: 11,
      includedTests: [
        createdTests[0]._id,
        createdTests[1]._id,
        createdTests[2]._id,
        createdTests[3]._id,
        createdTests[4]._id,
        createdTests[6]._id,
        createdTests[8]._id,
        createdTests[9]._id,
        createdTests[14]._id,
        createdTests[15]._id,
        createdTests[16]._id,
      ],
      recommendedFor: 'Individuals aged 35+ seeking a thorough preventative overview',
      image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=400',
    },
    {
      name: 'Advanced Cardiac & Metabolic Screening',
      slug: 'advanced-cardiac-metabolic-screening',
      description: 'Dedicated focus on heart health, arterial inflammation, high-sensitivity CRP, lipid fractions, HbA1c, and resting 12-lead ECG tracing.',
      shortDescription: 'Specialized cardiovascular defense and diabetes risk analysis.',
      price: 199,
      discountPrice: 159,
      duration: '2 Hours',
      testCount: 7,
      includedTests: [
        createdTests[0]._id,
        createdTests[2]._id,
        createdTests[3]._id,
        createdTests[9]._id,
        createdTests[10]._id,
        createdTests[14]._id,
        createdTests[18]._id,
      ],
      recommendedFor: 'Individuals with sedentary work, family history of heart disease, or elevated cholesterol',
      image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=400',
    },
    {
      name: 'Senior Vitality & Longevity Assessment',
      slug: 'senior-vitality-longevity-assessment',
      description: 'Tailored specifically for seniors, evaluating bone density vitamins, kidney GFR filtration, iron stores, metabolic balance, and chest radiography.',
      shortDescription: 'Senior-specific health, bone, and organ screening.',
      price: 260,
      discountPrice: 195,
      duration: '2.5 Hours',
      testCount: 9,
      includedTests: [
        createdTests[0]._id,
        createdTests[1]._id,
        createdTests[2]._id,
        createdTests[6]._id,
        createdTests[7]._id,
        createdTests[10]._id,
        createdTests[13]._id,
        createdTests[14]._id,
        createdTests[15]._id,
      ],
      recommendedFor: 'Seniors aged 60+ for proactive age-related health management',
      image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    },
    {
      name: 'Metabolic & Diabetes Care Package',
      slug: 'metabolic-diabetes-care-package',
      description: 'A focused screening package tracking long-term blood sugar control, lipid indicators, microalbumin urinalysis, and hepatic function.',
      shortDescription: 'Targeted diabetes screening and metabolic biomarker monitoring.',
      price: 140,
      discountPrice: 99,
      duration: '1.5 Hours',
      testCount: 6,
      includedTests: [
        createdTests[0]._id,
        createdTests[2]._id,
        createdTests[3]._id,
        createdTests[8]._id,
        createdTests[10]._id,
        createdTests[11]._id,
      ],
      recommendedFor: 'Individuals managing diabetes or pre-diabetes',
      image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=400',
    },
  ];

  const createdPackages: any[] = [];
  for (const pkg of packagesData) {
    const p = await HealthCheckupPackage.findOneAndUpdate(
      { slug: pkg.slug },
      { $set: pkg },
      { upsert: true, new: true }
    );
    createdPackages.push(p);
  }

  // 6. Facilities (5+ healthcare centers)
  console.log('[Seed] Seeding Healthcare Facilities...');
  const facilitiesData = [
    {
      name: 'Medicare Central Diagnostic Hub',
      slug: 'medicare-central-diagnostic-hub',
      type: 'DIAGNOSTIC_CENTER' as const,
      description: 'Our flagship state-of-the-art diagnostic imaging and high-throughput pathology laboratory center with accredited automated testing lines.',
      address: '742 Healthcare Parkway, Suite 100',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      phone: '+1 (212) 555-0190',
      email: 'central.lab@medicare.health',
      openingHours: 'Mon - Sun: 06:30 AM - 10:00 PM',
      services: ['Advanced Pathology', 'Digital Radiology (X-Ray)', 'Ultrasound', 'Cardiac Diagnostics', 'Home Sample Collection'],
      checkupPackages: [createdPackages[0]._id, createdPackages[1]._id, createdPackages[2]._id, createdPackages[3]._id, createdPackages[4]._id],
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=500',
      rating: 4.9,
      reviewCount: 312,
    },
    {
      name: 'Medicare Northside Specialty Clinic',
      slug: 'medicare-northside-specialty-clinic',
      type: 'PARTNER_CLINIC' as const,
      description: 'Comprehensive outpatient clinic hosting cardiology, neurology, and endocrinology consultation suites alongside on-site blood sample phlebotomy.',
      address: '1280 Lexington Avenue',
      city: 'New York',
      state: 'NY',
      postalCode: '10028',
      phone: '+1 (212) 555-0240',
      email: 'northside@medicare.health',
      openingHours: 'Mon - Fri: 08:00 AM - 08:00 PM | Sat: 09:00 AM - 04:00 PM',
      services: ['Doctor Consultations', 'Phlebotomy Station', 'Preventive Checkups', 'Telehealth Pods'],
      checkupPackages: [createdPackages[0]._id, createdPackages[1]._id, createdPackages[2]._id],
      image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=500',
      rating: 4.8,
      reviewCount: 184,
    },
    {
      name: 'Medicare Brooklyn Heights Diagnostic & Care',
      slug: 'medicare-brooklyn-heights-care',
      type: 'HEALTH_CHECKUP_CENTER' as const,
      description: 'Dedicated preventative checkup facility designed for rapid, comfortable patient throughput with executive lounge amenities.',
      address: '350 Henry Street',
      city: 'Brooklyn',
      state: 'NY',
      postalCode: '11201',
      phone: '+1 (718) 555-0322',
      email: 'brooklyn@medicare.health',
      openingHours: 'Mon - Sat: 07:00 AM - 07:00 PM',
      services: ['Executive Checkups', 'Cardiac Stress Testing', 'Diabetes Wellness', 'Dietary Consultations'],
      checkupPackages: [createdPackages[0]._id, createdPackages[1]._id, createdPackages[3]._id, createdPackages[4]._id],
      image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=500',
      rating: 4.9,
      reviewCount: 147,
    },
    {
      name: 'Medicare Queens Community Pharmacy & Lab',
      slug: 'medicare-queens-pharmacy-lab',
      type: 'PHARMACY' as const,
      description: 'Fully stocked full-service community pharmacy equipped with drive-through prescription dispensing and certified sample collection bays.',
      address: '92-15 Queens Boulevard',
      city: 'Rego Park',
      state: 'NY',
      postalCode: '11374',
      phone: '+1 (718) 555-0480',
      email: 'queens.pharmacy@medicare.health',
      openingHours: 'Open 24/7 (Pharmacy) | Lab: 07:00 AM - 09:00 PM',
      services: ['Prescription Dispensing', 'Vaccination Clinic', 'Blood Draw Station', 'OTC Consultations'],
      checkupPackages: [createdPackages[0]._id, createdPackages[4]._id],
      image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=500',
      rating: 4.7,
      reviewCount: 220,
    },
    {
      name: 'Medicare Express Collection Center Downtown',
      slug: 'medicare-express-collection-center-downtown',
      type: 'COLLECTION_CENTER' as const,
      description: 'Rapid 15-minute express blood and pathology collection center located near financial transit hubs for swift morning lab tests.',
      address: '15 Wall Street, Suite 402',
      city: 'New York',
      state: 'NY',
      postalCode: '10005',
      phone: '+1 (212) 555-0511',
      email: 'downtown.express@medicare.health',
      openingHours: 'Mon - Fri: 06:00 AM - 03:00 PM',
      services: ['Express Blood Draw', 'Urine Sample Drop', 'Courier Dispatch to Central Hub'],
      checkupPackages: [createdPackages[0]._id],
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=500',
      rating: 4.8,
      reviewCount: 96,
    },
  ];

  const createdFacilities: any[] = [];
  for (const fac of facilitiesData) {
    const f = await Facility.findOneAndUpdate(
      { slug: fac.slug },
      { $set: fac },
      { upsert: true, new: true }
    );
    createdFacilities.push(f);
  }

  // 7. Premium Membership Plan
  console.log('[Seed] Seeding Premium 1-Year Membership Plan...');
  const membershipPlanData = {
    name: 'Medicare Premium — 1 Year',
    slug: 'medicare-premium-1-year',
    description: 'All-inclusive comprehensive healthcare membership providing year-round preventative benefits, priority appointments, free delivery, and discounted diagnostics.',
    durationMonths: 12,
    price: 199,
    discountPrice: 149,
    features: [
      '1 Free Annual Comprehensive Health Checkup ($229 value)',
      'Unlimited FREE express medicine delivery (no minimum order)',
      'Priority booking access with zero wait queue for specialist doctors',
      '10% instant discount on all lab tests and pharmacy orders',
      '2 Complimentary Video Consultations with General Physicians',
      '24/7 Dedicated Priority Healthcare Concierge support',
    ],
    benefitsConfig: [
      {
        key: 'ANNUAL_CHECKUP',
        name: 'Complimentary Annual Health Checkup',
        description: 'One free full comprehensive executive health checkup redeemable anytime within membership year.',
        frequency: 'ONE_TIME' as const,
        maxLimit: 1,
      },
      {
        key: 'FREE_DELIVERY',
        name: 'Unlimited Free Medicine Express Delivery',
        description: 'Waives delivery fees on all medicine orders.',
        frequency: 'UNLIMITED' as const,
      },
      {
        key: 'PRIORITY_DOCTOR',
        name: 'Priority Doctor Consultations',
        description: 'Two complimentary telehealth appointments per membership year.',
        frequency: 'LIMITED_USE' as const,
        maxLimit: 2,
      },
      {
        key: 'STORE_DISCOUNT',
        name: '10% Extra Storewide Discount',
        description: 'Applied automatically to all medicines and diagnostics.',
        frequency: 'UNLIMITED' as const,
      },
    ],
    isActive: true,
  };

  const plan = await MembershipPlan.findOneAndUpdate(
    { slug: membershipPlanData.slug },
    { $set: membershipPlanData },
    { upsert: true, new: true }
  );

  console.log('\n=======================================================');
  console.log('✅ [System Baseline Configuration Synchronized]');
  console.log('  - Categories: synchronized');
  console.log('  - Formulary Medicines: synchronized');
  console.log('  - Diagnostic Tests: synchronized');
  console.log('  - Health Packages: synchronized');
  console.log('  - Healthcare Facilities: synchronized');
  console.log('  - Premium 1-Year Membership Plan: active');
  console.log('=======================================================\n');
}

// Allow direct execution
if (require.main === module) {
  runSeed()
    .then(async () => {
      await disconnectDatabase();
      process.exit(0);
    })
    .catch((err) => {
      console.error('[Seed Error]', err);
      process.exit(1);
    });
}
