import { Medicine } from '../../types';

export interface MedicineShowcaseItem extends Medicine {
  clinicalIndication: string;
  purchasedCount: string;
  categoryTag: string;
  badge?: string;
  discountPercentage?: number;
}

export interface PromoBentoItem {
  id: string;
  slug: string;
  title: string;
  discountText: string;
  price: number;
  subtitle: string;
  image: string;
  badgeColor: string;
  bgGradient: string;
  borderClass: string;
  accentColor: string;
  categoryTag: string;
  description: string;
  requiresPrescription: boolean;
  packSize: string;
  manufacturer: string;
}

export interface CategoryCircleItem {
  id: string;
  name: string;
  slug: string;
  iconName: 'Package' | 'Leaf' | 'Pill' | 'FlaskConical' | 'Activity' | 'Droplets' | 'Baby' | 'Stethoscope' | 'Dumbbell';
  bgColor: string;
  iconColor: string;
  haloColor: string;
  badgeCount?: number;
}

export const CATEGORY_CIRCLES: CategoryCircleItem[] = [
  {
    id: 'cat-all',
    name: 'All Products',
    slug: 'all',
    iconName: 'Package',
    bgColor: 'bg-rose-50 hover:bg-rose-100',
    iconColor: 'text-rose-600',
    haloColor: 'group-hover:ring-rose-400',
    badgeCount: 16,
  },
  {
    id: 'cat-herbal',
    name: 'Herbal Care',
    slug: 'herbal-care',
    iconName: 'Leaf',
    bgColor: 'bg-amber-50 hover:bg-amber-100',
    iconColor: 'text-amber-600',
    haloColor: 'group-hover:ring-amber-400',
    badgeCount: 8,
  },
  {
    id: 'cat-medicine',
    name: 'Medicine',
    slug: 'medicine',
    iconName: 'Pill',
    bgColor: 'bg-cyan-50 hover:bg-cyan-100',
    iconColor: 'text-cyan-600',
    haloColor: 'group-hover:ring-cyan-400',
    badgeCount: 12,
  },
  {
    id: 'cat-lab-tests',
    name: 'Lab Tests',
    slug: 'lab-tests',
    iconName: 'FlaskConical',
    bgColor: 'bg-purple-50 hover:bg-purple-100',
    iconColor: 'text-purple-600',
    haloColor: 'group-hover:ring-purple-400',
    badgeCount: 5,
  },
  {
    id: 'cat-healthcare',
    name: 'Healthcare',
    slug: 'healthcare',
    iconName: 'Activity',
    bgColor: 'bg-emerald-50 hover:bg-emerald-100',
    iconColor: 'text-emerald-600',
    haloColor: 'group-hover:ring-emerald-400',
    badgeCount: 9,
  },
  {
    id: 'cat-ayurvedic',
    name: 'Ayurvedic care',
    slug: 'ayurvedic-care',
    iconName: 'Droplets',
    bgColor: 'bg-orange-50 hover:bg-orange-100',
    iconColor: 'text-orange-600',
    haloColor: 'group-hover:ring-orange-400',
    badgeCount: 6,
  },
  {
    id: 'cat-baby',
    name: 'Mother and baby care',
    slug: 'mother-and-baby-care',
    iconName: 'Baby',
    bgColor: 'bg-pink-50 hover:bg-pink-100',
    iconColor: 'text-pink-600',
    haloColor: 'group-hover:ring-pink-400',
    badgeCount: 7,
  },
  {
    id: 'cat-devices',
    name: 'Healthcare devices',
    slug: 'healthcare-devices',
    iconName: 'Stethoscope',
    bgColor: 'bg-sky-50 hover:bg-sky-100',
    iconColor: 'text-sky-600',
    haloColor: 'group-hover:ring-sky-400',
    badgeCount: 4,
  },
  {
    id: 'cat-fitness',
    name: 'Fitness Supplements',
    slug: 'fitness-supplements',
    iconName: 'Dumbbell',
    bgColor: 'bg-lime-50 hover:bg-lime-100',
    iconColor: 'text-lime-700',
    haloColor: 'group-hover:ring-lime-400',
    badgeCount: 6,
  },
];

// Top Trending 4 Products
export const TRENDING_PRODUCTS: MedicineShowcaseItem[] = [
  {
    _id: 'med-trend-01',
    name: 'Cardioplus Remedy',
    slug: 'cardioplus-remedy',
    genericName: 'Cardiovascular Support Complex',
    brand: 'CardioVital Labs',
    clinicalIndication: 'Heart Health',
    purchasedCount: '6k Purchased',
    categoryTag: 'Healthcare',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 140,
    sku: 'MED-CARDIO-PLUS',
    manufacturer: 'CardioVital Laboratories',
    dosageForm: 'Capsule',
    strength: '600mg',
    packSize: 'Bottle of 60 Capsules',
    requiresPrescription: false,
    description: 'Advanced clinical cardiac support formulated with CoQ10, hawthorn berry, and magnesium to promote healthy vascular function and arterial elasticity.',
    shortDescription: 'Clinical cardiac support with CoQ10 & Hawthorn for vascular wellness.',
    ingredients: ['Coenzyme Q10 200mg', 'Hawthorn Berry Extract 250mg', 'Magnesium Citrate 150mg'],
    images: ['/images/medicines/cardiocare_bottle.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 382,
  },
  {
    _id: 'med-trend-02',
    name: 'HeartEase Solution',
    slug: 'heartease-solution',
    genericName: 'Botanical Circulatory Tincture',
    brand: 'HeartEase Botanicals',
    clinicalIndication: 'Circulatory System',
    purchasedCount: '6k Purchased',
    categoryTag: 'Herbal Care',
    category: 'Vitamins & Dietary Supplements',
    price: 75.0,
    discountPrice: 70.0,
    stock: 95,
    sku: 'MED-HEART-EASE-SOL',
    manufacturer: 'HeartEase Botanicals Inc',
    dosageForm: 'Liquid Tincture',
    strength: '30ml Dropper',
    packSize: '1 Fl Oz (30ml) Bottle',
    requiresPrescription: false,
    description: 'Organically crafted herbal heart tincture with bioactive hawthorn berry and elderberry extract for steady peripheral circulation and daily micro-vascular health.',
    shortDescription: 'Organic botanical heart tincture for steady micro-vascular flow.',
    ingredients: ['Organic Hawthorn Extract', 'Ginkgo Biloba Extract', 'Hibiscus Flower Tincture'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 298,
  },
  {
    _id: 'med-trend-03',
    name: 'Vasodilate Plus',
    slug: 'vasodilate-plus',
    genericName: 'Nitric Oxide Vasodilator',
    brand: 'VasoTech Bio',
    clinicalIndication: 'Cardiac Care',
    purchasedCount: '6k Purchased',
    categoryTag: 'Fitness Supplements',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 120,
    sku: 'MED-VASODILATE-PLUS',
    manufacturer: 'VasoTech Biopharma',
    dosageForm: 'Capsule',
    strength: '750mg',
    packSize: 'Bottle of 90 Capsules',
    requiresPrescription: false,
    description: 'High potency nitric oxide precursor formula supporting relaxed endothelial tissue, optimal blood vessel dilation, and efficient cardio flow during physical activity.',
    shortDescription: 'Nitric oxide vasodilator formula for relaxed endothelial function.',
    ingredients: ['L-Arginine Alpha-Ketoglutarate', 'L-Citrulline Malate', 'Beet Root Extract'],
    images: ['/images/medicines/vasodilate_plus.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 412,
  },
  {
    _id: 'med-trend-04',
    name: 'BloodFlow Booster',
    slug: 'bloodflow-booster',
    genericName: 'Vascular Vein Strength Formula',
    brand: 'Vitality Labs',
    clinicalIndication: 'Vascular Health',
    purchasedCount: '6k Purchased',
    categoryTag: 'Healthcare',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 160,
    sku: 'MED-REDBOOST-01',
    manufacturer: 'Vitality Labs US',
    dosageForm: 'Capsule',
    strength: '500mg',
    packSize: 'Bottle of 60 Capsules',
    requiresPrescription: false,
    description: 'Synergistic micro-nutrient complex designed to reinforce vein wall integrity, reduce lower extremity fatigue, and support robust systemic blood flow.',
    shortDescription: 'Reinforces vein wall strength and systemic blood circulation.',
    ingredients: ['Diosmin 450mg', 'Hesperidin 50mg', 'Vitamin C 100mg', 'Rutin Bioflavonoid'],
    images: ['/images/medicines/red_boost.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 520,
  },
];

// Promotional Bento Banners
export const BENTO_PROMOS: PromoBentoItem[] = [
  {
    id: 'promo-bloodflow',
    slug: 'bloodflow-plus-capsules',
    title: 'BloodFlow Plus',
    discountText: '25% off',
    price: 70.0,
    subtitle: 'including tax',
    image: '/images/medicines/bloodflow_trio.jpg',
    badgeColor: 'bg-white/95 text-emerald-950 font-bold',
    bgGradient: 'bg-gradient-to-br from-[#dff2f0] via-[#e5f5f3] to-[#d4ece7]',
    borderClass: 'border-[#bfe5df]',
    accentColor: 'text-emerald-900',
    categoryTag: 'Fitness Supplements',
    description: 'Clinically balanced 3-pack cardiovascular formulation engineered for maximum endothelial dilation, arterial resilience, and daily vitality.',
    requiresPrescription: false,
    packSize: 'Pack of 3 x 60 Capsules',
    manufacturer: 'CardioFlow Labs International',
  },
  {
    id: 'promo-sanitizer',
    slug: 'pureguard-hand-sanitizer',
    title: 'Hand Sanitizer',
    discountText: '25% off',
    price: 22.9,
    subtitle: 'including tax',
    image: '/images/medicines/hand_sanitizer.jpg',
    badgeColor: 'bg-white/95 text-indigo-950 font-bold',
    bgGradient: 'bg-gradient-to-br from-[#ede8fa] via-[#f1edfc] to-[#e4dcf8]',
    borderClass: 'border-[#dccefb]',
    accentColor: 'text-indigo-950',
    categoryTag: 'Healthcare',
    description: 'Hospital-grade 70% Ethyl Alcohol antiseptic hand sanitizer with moisturizing organic Aloe Vera and soothing Vitamin E beadlets.',
    requiresPrescription: false,
    packSize: '2 x 500ml Dispenser Pump Bottles',
    manufacturer: 'PureGuard Healthcare Diagnostics',
  },
  {
    id: 'promo-lotion',
    slug: 'dermaglow-body-lotion',
    title: 'Body Lotion',
    discountText: '20% off',
    price: 29.0,
    subtitle: 'including tax',
    image: '/images/medicines/body_lotion.jpg',
    badgeColor: 'bg-white/95 text-amber-950 font-bold',
    bgGradient: 'bg-gradient-to-br from-[#faf0dc] via-[#fbf3e5] to-[#f4e4c7]',
    borderClass: 'border-[#edd8ae]',
    accentColor: 'text-amber-950',
    categoryTag: 'Mother and baby care',
    description: 'Hypoallergenic ceramide barrier repair lotion with prebiotic oat extract for 24-hour sensitive skin hydration and dermatological care.',
    requiresPrescription: false,
    packSize: '300ml Pump Bottle + 150ml Travel Tube',
    manufacturer: 'DermaGlow Clinical Skin Science',
  },
];

// Main 8-Grid Showcase Products Matching Screenshot
export const GRID_MEDICINES: MedicineShowcaseItem[] = [
  {
    _id: 'med-grid-01',
    name: 'PressureRelief Formula',
    slug: 'pressurerelief-formula',
    genericName: 'Florin Fast-Acting Decongestant Analgesic',
    brand: 'Florin Medical',
    clinicalIndication: 'Blood Flow Management',
    purchasedCount: '6k Purchased',
    categoryTag: 'Medicine',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 220,
    sku: 'MED-FLORIN-RELIEF',
    manufacturer: 'Florin Pharmaceuticals',
    dosageForm: 'Capsule',
    strength: '500mg / 120mg',
    packSize: 'Pack of 32 Dual-Tone Capsules',
    requiresPrescription: false,
    description: 'Dual-action medical formula relieving acute pressure build-up, sinus discomfort, and cranial tension with rapid systemic bioavailability.',
    shortDescription: 'Rapid relief for cranial & systemic vascular pressure tension.',
    ingredients: ['Paracetamol 500mg', 'Pseudoephedrine HCl 120mg'],
    images: ['/images/medicines/florin_box.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 462,
  },
  {
    _id: 'med-grid-02',
    name: 'CardioCare Supplement',
    slug: 'cardiocare-supplement',
    genericName: 'CardioVital Heart Wellness Formula',
    brand: 'CardioVital',
    clinicalIndication: 'Heart Function',
    purchasedCount: '6k Purchased',
    categoryTag: 'Healthcare',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 190,
    sku: 'MED-CARDIOVITAL-60',
    manufacturer: 'CardioVital Wellness Group',
    dosageForm: 'Vegetarian Capsule',
    strength: '600mg',
    packSize: 'Bottle of 60 Vegetarian Capsules',
    requiresPrescription: false,
    description: 'Targeted cardiac nutrient matrix delivering Coenzyme Q10, EPA/DHA Omega-3s, and hawthorn bioflavonoids to optimize myocardial contraction strength.',
    shortDescription: 'Targeted cardiac nutrient matrix for peak myocardial contractility.',
    ingredients: ['Omega-3 Triglycerides 400mg', 'CoQ10 100mg', 'Hawthorn Extract 100mg'],
    images: ['/images/medicines/cardiocare_bottle.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 310,
  },
  {
    _id: 'med-grid-03',
    name: 'Hypertension Helper',
    slug: 'hypertension-helper',
    genericName: 'Digital Upper-Arm Blood Pressure Monitor',
    brand: 'HealthCheck Medical',
    clinicalIndication: 'Cardiovascular Wellness',
    purchasedCount: '6k Purchased',
    categoryTag: 'Healthcare devices',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 85,
    sku: 'DEV-BP-MONITOR-700',
    manufacturer: 'HealthCheck Precision Instruments',
    dosageForm: 'Medical Device',
    strength: 'Clinically Validated Accuracy',
    packSize: 'Monitor Unit + Adult Arm Cuff + Storage Box',
    requiresPrescription: false,
    description: 'Hospital-grade digital upper-arm blood pressure and pulse monitor featuring WHO indicator bar, irregular heartbeat detection, and 2-user 120 memory log.',
    shortDescription: 'Hospital-grade digital upper-arm blood pressure & pulse monitor.',
    ingredients: ['Oscillometric Pressure Sensor', 'Bio-Compatible Nylon Cuff'],
    images: ['/images/medicines/bp_monitor.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 520,
  },
  {
    _id: 'med-grid-04',
    name: 'VitalFlow Medicine',
    slug: 'vitalflow-medicine',
    genericName: 'Micro-Vascular Nitric Oxide Enhancer',
    brand: 'Vitality Labs',
    clinicalIndication: 'Heart Disease Prevention',
    purchasedCount: '6k Purchased',
    categoryTag: 'Medicine',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 145,
    sku: 'MED-VITALFLOW-04',
    manufacturer: 'Vitality Pharmaceutical Care',
    dosageForm: 'Capsule',
    strength: '500mg',
    packSize: 'Pack of 60 Daily Capsules',
    requiresPrescription: false,
    description: 'Comprehensive preventative cardiovascular blend engineered to inhibit oxidative stress within coronary arteries and encourage smooth laminar blood flow.',
    shortDescription: 'Coronary artery protection and smooth laminar blood circulation.',
    ingredients: ['Resveratrol 150mg', 'Grape Seed Extract 200mg', 'L-Arginine 150mg'],
    images: ['/images/medicines/red_boost.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 290,
  },
  {
    _id: 'med-grid-05',
    name: 'CardioCare Medic',
    slug: 'cardiocare-medic',
    genericName: 'Anti-Atherosclerotic Vascular Support',
    brand: 'CardioCare',
    clinicalIndication: 'Circulatory Wellness',
    purchasedCount: '6k Purchased',
    categoryTag: 'Medicine',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 110,
    sku: 'MED-CARDIOCARE-MEDIC',
    manufacturer: 'Celltris UK Pharma',
    dosageForm: 'Capsule',
    strength: '40mg Active Formulation',
    packSize: 'Amber Glass Bottle of 60 Capsules',
    requiresPrescription: false,
    description: 'Clinical prescription-strength supportive remedy designed to support peripheral vessel dilation, reduce circulatory resistance, and stabilize arterial tone.',
    shortDescription: 'Peripheral vessel dilation and circulatory resistance relief.',
    ingredients: ['Cardioxivitamins Complex 40mg', 'Bioflavonoid Matrix 100mg'],
    images: ['/images/medicines/cardiocare_medic.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 388,
  },
  {
    _id: 'med-grid-06',
    name: 'HeartEase Formula',
    slug: 'heartease-formula',
    genericName: 'Bioactive Hawthorne Herbal Complex',
    brand: 'HeartEase Botanicals',
    clinicalIndication: 'Heart and Vessel Health',
    purchasedCount: '6k Purchased',
    categoryTag: 'Herbal Care',
    category: 'Vitamins & Dietary Supplements',
    price: 75.0,
    discountPrice: 70.0,
    stock: 130,
    sku: 'MED-HEARTEASE-HERB',
    manufacturer: 'HeartEase Botanicals LLC',
    dosageForm: 'Liquid Dropper',
    strength: '30ml Extract',
    packSize: '1 Fl Oz (30ml) Dropper Bottle',
    requiresPrescription: false,
    description: 'Holistic organic herbal tincture combining wild-harvested hawthorn berries, motherwort, and passionflower to soothe cardiac tension and promote balanced blood pressure.',
    shortDescription: 'Wild-harvested organic botanical drops for balanced blood pressure.',
    ingredients: ['Hawthorn Berry Extract', 'Motherwort Aerial Parts', 'Organic Cane Alcohol'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 410,
  },
  {
    _id: 'med-grid-07',
    name: 'VitalHeart Solution',
    slug: 'vitalheart-solution',
    genericName: 'Ayurvedic Arjuna Cardiac Elixir',
    brand: 'VitalHeart Ayurveda',
    clinicalIndication: 'Cardiac Support',
    purchasedCount: '6k Purchased',
    categoryTag: 'Ayurvedic care',
    category: 'Vitamins & Dietary Supplements',
    price: 75.0,
    discountPrice: 70.0,
    stock: 175,
    sku: 'MED-VITALHEART-SOL',
    manufacturer: 'VitalHeart Ayurvedic Science',
    dosageForm: 'Herbal Tincture',
    strength: '100% Pure Botanical',
    packSize: 'Amber Bottle with Precision Dropper 30ml',
    requiresPrescription: false,
    description: 'Time-tested Ayurvedic formulation with Terminalia Arjuna bark extract and Ashwagandha to tone heart muscles, combat physical stress, and calm nervous palpitation.',
    shortDescription: 'Ayurvedic Terminalia Arjuna cardiac tonic for muscular tone.',
    ingredients: ['Terminalia Arjuna Bark Extract 500mg', 'Ashwagandha Withania Somnifera 200mg'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 345,
  },
  {
    _id: 'med-grid-08',
    name: 'BloodFlow Plus',
    slug: 'bloodflow-plus-single',
    genericName: 'Cardiovascular Nitric Amino Stack',
    brand: 'BloodFlow Pro',
    clinicalIndication: 'Vascular Care',
    purchasedCount: '6k Purchased',
    categoryTag: 'Fitness Supplements',
    category: 'Cardiovascular & Blood Pressure',
    price: 75.0,
    discountPrice: 70.0,
    stock: 250,
    sku: 'MED-BLOODFLOW-PLUS-SINGLE',
    manufacturer: 'CardioFlow Labs International',
    dosageForm: 'Vegetarian Capsule',
    strength: '600mg',
    packSize: 'Pack of 3 Bottles (180 Total Capsules)',
    requiresPrescription: false,
    description: 'The premier multi-bottle regimen providing round-the-clock cardiovascular, endothelial, and capillary support with nitric oxide precursors and antioxidant bioflavonoids.',
    shortDescription: 'Premier round-the-clock vascular and endothelial bio-support.',
    ingredients: ['L-Citrulline Malate 500mg', 'Nitric Booster Blend 300mg', 'Pine Bark Extract 100mg'],
    images: ['/images/medicines/bloodflow_trio.jpg'],
    status: 'ACTIVE',
    rating: 4.5,
    reviewCount: 680,
  },
  // Additional Products for complete coverage across all categories:
  {
    _id: 'med-grid-09',
    name: 'Advanced Cardio & Lipid Lab Panel',
    slug: 'cardio-lipid-lab-panel',
    genericName: 'Diagnostic Blood Chemistry Profile',
    brand: 'Medicare Diagnostics',
    clinicalIndication: 'Diagnostic Screening',
    purchasedCount: '4.8k Booked',
    categoryTag: 'Lab Tests',
    category: 'Cardiovascular & Blood Pressure',
    price: 95.0,
    discountPrice: 70.0,
    stock: 500,
    sku: 'LAB-CARDIO-PANEL-01',
    manufacturer: 'Medicare Central Clinical Labs',
    dosageForm: 'Home Sample Collection / Clinic Walk-in',
    strength: '14 Vital Biomarkers',
    packSize: 'Full Verified Digital Report in 12 Hours',
    requiresPrescription: false,
    description: 'Comprehensive blood biomarker screening including Total Cholesterol, HDL/LDL, Triglycerides, hs-CRP cardiac inflammation marker, and HbA1c glucose level.',
    shortDescription: '14 vital heart biomarkers with cold-chain home nurse blood draw.',
    ingredients: ['Certified Phlebotomy Draw', 'Biochemical Serum Analysis'],
    images: ['/images/medicines/bp_monitor.jpg'],
    status: 'ACTIVE',
    rating: 4.9,
    reviewCount: 512,
  },
  {
    _id: 'med-grid-10',
    name: 'DermaGlow Nourish Body Care',
    slug: 'dermaglow-gentle-lotion',
    genericName: 'Ceramide Prebiotic Skin Hydration',
    brand: 'DermaGlow Clinical',
    clinicalIndication: 'Barrier Moisture Therapy',
    purchasedCount: '7.2k Purchased',
    categoryTag: 'Mother and baby care',
    category: 'Skin Care & Dermatology',
    price: 35.0,
    discountPrice: 29.0,
    stock: 310,
    sku: 'SKN-DERMAGLOW-300',
    manufacturer: 'DermaGlow Clinical Skin Science',
    dosageForm: 'Lotion + Cream Tube',
    strength: 'Dermatologist Tested',
    packSize: '300ml Pump Dispenser + 150ml Tube',
    requiresPrescription: false,
    description: 'Gentle, pediatrician and dermatologist-approved soothing lotion for expectant mothers, newborns, and sensitive skins prone to eczema and irritation.',
    shortDescription: 'Pediatrician-tested hypoallergenic ceramide moisture formula.',
    ingredients: ['Ceramide NP', 'Colloidal Oatmeal 2%', 'Hyaluronic Acid'],
    images: ['/images/medicines/body_lotion.jpg'],
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 420,
  },
  {
    _id: 'med-grid-11',
    name: 'PureGuard Antibacterial Care Gel',
    slug: 'pureguard-care-gel',
    genericName: 'Ethyl Alcohol 70% Hand Sanitizer',
    brand: 'PureGuard Health',
    clinicalIndication: 'Infection Prevention',
    purchasedCount: '9.4k Purchased',
    categoryTag: 'Healthcare',
    category: 'Antibiotics & Anti-Infectives',
    price: 28.0,
    discountPrice: 22.9,
    stock: 450,
    sku: 'HLT-PUREGUARD-500',
    manufacturer: 'PureGuard Laboratories',
    dosageForm: 'Antiseptic Gel',
    strength: '70% v/v Isopropyl Formulation',
    packSize: 'Twin Pack 2 x 500ml Dispenser Bottles',
    requiresPrescription: false,
    description: 'High efficacy antimicrobial rinse-free hand sanitizer with aloe and glycerin to kill 99.9% of bacteria and viruses without stripping essential skin oils.',
    shortDescription: 'Kills 99.9% of pathogens with skin-calming aloe vera hydration.',
    ingredients: ['Ethyl Alcohol 70%', 'Aloe Barbadensis Leaf Juice', 'Tocopheryl Acetate'],
    images: ['/images/medicines/hand_sanitizer.jpg'],
    status: 'ACTIVE',
    rating: 4.8,
    reviewCount: 630,
  },
  {
    _id: 'med-grid-12',
    name: 'AyurSoothe Cardamom & Arjuna Tea',
    slug: 'ayursoothe-cardiac-tea',
    genericName: 'Herbal Cardio Infusion',
    brand: 'AyurSoothe',
    clinicalIndication: 'Ayurvedic Wellness',
    purchasedCount: '3.9k Purchased',
    categoryTag: 'Ayurvedic care',
    category: 'Vitamins & Dietary Supplements',
    price: 32.0,
    discountPrice: 26.0,
    stock: 200,
    sku: 'AYUR-TEA-ARJUNA-50',
    manufacturer: 'AyurSoothe Holistic Herbals',
    dosageForm: 'Infusion Bags',
    strength: 'Organic Whole Herbs',
    packSize: 'Tin of 40 Biodegradable Sachets',
    requiresPrescription: false,
    description: 'Delicate Ayurvedic caffeine-free infusion featuring organic Arjuna bark, green cardamom, cinnamon, and sacred holy basil (Tulsi) for emotional and vascular balance.',
    shortDescription: 'Caffeine-free organic Arjuna & Tulsi cardiac herbal infusion.',
    ingredients: ['Arjuna Bark', 'Green Cardamom', 'Holy Basil Tulsi', 'Cinnamon'],
    images: ['/images/medicines/heartease_herbal.jpg'],
    status: 'ACTIVE',
    rating: 4.7,
    reviewCount: 195,
  }
];
